/**
 * Validation evidence, as a compiled module.
 *
 * GENERATED by the validation suites — edit those, not this.
 *
 * A module rather than a JSON file read at startup, because the runtime image copies
 * `packages/` and not `docs/`: the file was never present in a deployed environment and
 * every application reported not_tested. Committed, so a change to what the framework
 * claims about itself shows up in a diff next to the code it claims about.
 *
 * Each record names the commit it was validated at. Nothing here verifies the running
 * build is that commit — the container has no way to know its own — so the commit is
 * carried through to the API rather than checked. A reader can compare it; the framework
 * does not pretend to.
 */

import type { ApplicationEvidenceIndex } from './application-evidence';

export const RECORDED_APPLICATION_EVIDENCE: ApplicationEvidenceIndex = Object.freeze({
  'approval-workbench': {
    appId: 'approval-workbench',
    status: 'pass',
    environment: 'dev',
    suite: 'npm run validate:approval-workbench',
    commit: '205cd5e801521f6c03bd84d40e5ba4bbdea93bc6',
    validatedAt: '2026-08-30T06:22:48.215Z',
    checks: {
      total: 33,
      passed: 33,
      failed: 0,
    },
    evidenceRef: 'docs/validation/approval-workbench-latest.json',
  },
});
