/**
 * Identifier aliases.
 *
 * These are documentation-grade aliases rather than branded types: the goal is
 * readable signatures (`findMember(organizationId, userId)`) without forcing
 * every call site through a cast. Persisted identifiers are CUIDs generated by
 * Prisma; request identifiers are generated by @trustos/logging.
 */
export type Id = string;

export type UserId = Id;
export type OrganizationId = Id;
export type RoleId = Id;
export type PermissionId = Id;
export type MembershipId = Id;
export type AuditLogId = Id;

/** Correlation identifier attached to every request, log line and audit record. */
export type RequestId = string;

/** ISO-8601 timestamp string as it crosses the API boundary. */
export type IsoDateTime = string;

/** Fields every persisted framework entity carries. */
export interface Timestamped {
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

/**
 * Soft-delete marker. `deletedAt === null` means "live"; any other value means
 * the row is logically deleted and must be excluded from ordinary reads.
 */
export interface SoftDeletable {
  deletedAt: IsoDateTime | null;
}
