import { randomUUID } from 'node:crypto';
import { ApiError } from '@trustos/errors';
import type { AuditService } from '@trustos/audit';
import type { LoggerPort } from '@trustos/logging';
import type { MetricsRecorder } from '@trustos/observability';
import type { ToolCall, ToolDefinition } from '@trustos/ai-sdk';
import {
  parseArguments,
  resolveCall,
  serialiseResult,
  toToolDefinition,
  type FunctionCallContext,
  type FunctionDefinition,
  type FunctionResult,
} from '@trustos/function-calling';

/**
 * The tool registry and executor.
 *
 * **A tool call is a privileged action taken on the strength of a model's judgement.** That is the
 * sentence the whole package is built around. The model decided to call `refund_order`; the model
 * can be wrong, confused, or acting on injected instructions in a support ticket. Nothing about
 * the call being generated by an AI makes it safer than a request from an untrusted client, and
 * it is checked accordingly:
 *
 *   1. **The tool must be registered.** A call to something that does not exist is answered, not
 *      executed.
 *   2. **The agent must be allowed to call it.** Declared on the agent, checked here.
 *   3. **The actor must hold the permission.** The *person's* permission, not the agent's — an
 *      agent acting for a support representative must not do things that representative cannot.
 *      This is the check that makes prompt injection survivable: an injected instruction to
 *      transfer funds fails because the person on whose behalf the agent is acting cannot
 *      transfer funds.
 *   4. **Arguments are validated** against the declared schema.
 *   5. **It runs with a timeout**, so a hanging tool does not hang the agent.
 *   6. **It is audited**, whether it succeeded or not.
 *
 * A failure at any step is *returned to the model* rather than thrown. The model reads it and
 * corrects, which is how a tool loop is supposed to work — an exception ends a conversation that
 * was one turn from working.
 */

/**
 * The context for one batch of calls.
 *
 * `callId` is deliberately *not* part of it: the executor sets it per call from the call itself.
 * A batch context carrying a single call id would hand every handler in the batch the first
 * call's id, and a tool that correlates its work by that id would attribute all of it to one
 * call.
 */
export interface ToolExecutionContext extends Omit<FunctionCallContext, 'callId'> {
  /** Permissions the *actor* holds. Not the agent's — see the header. */
  actorPermissions: string[];
  /** Tools this agent may call. */
  allowedTools: string[];
}

export interface ToolExecutionOptions {
  functions?: FunctionDefinition[];
  audit?: Pick<AuditService, 'record'>;
  logger?: LoggerPort;
  metrics?: MetricsRecorder;
  /** Default ceiling per call, when a function does not declare one. */
  defaultTimeoutMs?: number;
  /** Bound on how much a result may add to the next prompt. */
  maxResultChars?: number;
  now?: () => Date;
  newId?: (prefix: string) => string;
}

export const TOOL_METRICS = {
  CALLS: 'ai.tool.calls',
  DENIED: 'agent.tool.denied',
  FAILED: 'agent.tool.failed',
  DURATION_MS: 'ai.tool.duration_ms',
  TIMEOUT: 'ai.tool.timeout',
} as const;

export class ToolRegistry {
  private readonly functions = new Map<string, FunctionDefinition>();
  private readonly now: () => Date;
  private readonly newId: (prefix: string) => string;

  constructor(private readonly options: ToolExecutionOptions = {}) {
    this.now = options.now ?? (() => new Date());
    this.newId = options.newId ?? ((prefix) => `${prefix}_${randomUUID()}`);

    for (const definition of options.functions ?? []) this.register(definition);
  }

  register<TArgs, TResult>(definition: FunctionDefinition<TArgs, TResult>): this {
    if (this.functions.has(definition.name)) {
      throw ApiError.conflict(
        `A tool called "${definition.name}" is already registered. Which one the model reached ` +
          'would depend on registration order.',
        { reason: 'tool_conflict', tool: definition.name },
      );
    }

    // Validated at registration, so a name a provider would reject fails at start-up rather than
    // on the first agent run.
    toToolDefinition(definition as FunctionDefinition);

    this.functions.set(definition.name, definition as FunctionDefinition);
    return this;
  }

  registerAll(definitions: FunctionDefinition[]): this {
    for (const definition of definitions) this.register(definition);
    return this;
  }

  has(name: string): boolean {
    return this.functions.has(name);
  }

  get(name: string): FunctionDefinition | null {
    return this.functions.get(name) ?? null;
  }

  /**
   * The tool definitions to send to a model.
   *
   * Filtered by what the agent may call **and** what the actor may do. A tool the actor cannot use
   * is not offered — otherwise the model calls it, gets a permission error, and spends a turn
   * discovering something the prompt could have avoided.
   */
  definitionsFor(input: { allowedTools: string[]; actorPermissions: string[] }): ToolDefinition[] {
    return [...this.functions.values()]
      .filter((definition) => input.allowedTools.includes(definition.name))
      .filter(
        (definition) =>
          !definition.permission || input.actorPermissions.includes(definition.permission),
      )
      .map((definition) => toToolDefinition(definition))
      .sort((a, b) => a.name.localeCompare(b.name));
  }

  /**
   * Runs one tool call.
   *
   * Never throws. Every failure — unknown tool, denied permission, bad arguments, timeout, a
   * handler that threw — comes back as a result the model can read.
   */
  async execute(call: ToolCall, context: ToolExecutionContext): Promise<FunctionResult> {
    const startedAt = Date.now();

    const resolved = resolveCall(call, this.functions);

    if (!resolved.ok) {
      await this.auditDenied(call, context, resolved.error);
      this.options.metrics?.increment(TOOL_METRICS.DENIED, 1, {
        tool: call.name,
        reason: 'unknown',
      });
      return this.failure(call, resolved.error, startedAt);
    }

    const definition = resolved.definition;

    if (!context.allowedTools.includes(definition.name)) {
      const error =
        `The agent is not permitted to call "${definition.name}". ` +
        `It may call: ${context.allowedTools.join(', ') || '(none)'}.`;

      await this.auditDenied(call, context, error);
      this.options.metrics?.increment(TOOL_METRICS.DENIED, 1, { tool: call.name, reason: 'agent' });
      return this.failure(call, error, startedAt);
    }

    if (definition.permission && !context.actorPermissions.includes(definition.permission)) {
      /*
       * The actor's permission, not the agent's.
       *
       * This is the check that makes prompt injection survivable. An instruction hidden in a
       * support ticket telling the agent to transfer funds fails here, because the support
       * representative on whose behalf it is acting cannot transfer funds — and no wording in the
       * ticket changes that.
       */
      const error =
        `You do not have permission to use "${definition.name}". This is a permission held by ` +
        'the person on whose behalf you are acting, and it cannot be granted by asking.';

      await this.auditDenied(call, context, error);
      this.options.metrics?.increment(TOOL_METRICS.DENIED, 1, {
        tool: call.name,
        reason: 'permission',
      });
      return this.failure(call, error, startedAt);
    }

    const parsed = parseArguments(definition, call.arguments);

    if (!parsed.ok) {
      this.options.metrics?.increment(TOOL_METRICS.FAILED, 1, {
        tool: call.name,
        reason: 'arguments',
      });
      // Returned, not thrown: a model given "amount should be number and was string" fixes it on
      // the next turn.
      return this.failure(call, parsed.error!, startedAt);
    }

    this.options.metrics?.increment(TOOL_METRICS.CALLS, 1, { tool: definition.name });

    const timeoutMs = definition.timeoutMs ?? this.options.defaultTimeoutMs ?? 30_000;
    const controller = new AbortController();
    const onAbort = () => controller.abort();
    context.signal.addEventListener('abort', onAbort, { once: true });
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const value = await Promise.race([
        definition.handler(parsed.args, {
          ...context,
          // From the call, not the batch. See ToolExecutionContext.
          callId: call.id,
          signal: controller.signal,
        }),
        new Promise<never>((_, reject) => {
          controller.signal.addEventListener(
            'abort',
            () => {
              const error = new Error(
                `The tool "${definition.name}" did not finish within ${timeoutMs}ms.`,
              );
              error.name = 'ToolTimeoutError';
              reject(error);
            },
            { once: true },
          );
        }),
      ]);

      const durationMs = Date.now() - startedAt;
      this.options.metrics?.observe(TOOL_METRICS.DURATION_MS, durationMs, {
        tool: definition.name,
      });

      await this.auditCall(call, context, definition, true, durationMs, null);

      return {
        callId: call.id,
        name: definition.name,
        ok: true,
        content: serialiseResult(value, this.options.maxResultChars),
        value,
        durationMs,
      };
    } catch (error) {
      const durationMs = Date.now() - startedAt;
      const timedOut = (error as { name?: string }).name === 'ToolTimeoutError';

      this.options.metrics?.increment(timedOut ? TOOL_METRICS.TIMEOUT : TOOL_METRICS.FAILED, 1, {
        tool: definition.name,
      });

      const message = error instanceof Error ? error.message : String(error);

      this.options.logger?.warn(
        {
          tool: definition.name,
          agentId: context.agentId,
          organizationId: context.organizationId,
          durationMs,
          error: message,
        },
        'tool call failed',
      );

      await this.auditCall(call, context, definition, false, durationMs, message);

      /*
       * The error the model sees is deliberately not the raw one.
       *
       * A stack trace or an internal message tells the model things about the system it should
       * not be reasoning about, and it can end up quoted to a customer. What it gets is enough to
       * decide whether to retry or to say it could not do the thing.
       */
      return this.failure(
        call,
        timedOut
          ? `The tool "${definition.name}" timed out. It may be worth trying once more, or telling the user this is unavailable.`
          : `The tool "${definition.name}" failed. Do not retry with the same arguments; tell the user it could not be completed.`,
        startedAt,
      );
    } finally {
      clearTimeout(timer);
      context.signal.removeEventListener('abort', onAbort);
    }
  }

  /**
   * Runs several calls.
   *
   * Read-only calls run concurrently; a mutating one runs alone and in order. A model asking for
   * three lookups should not wait three times, and two concurrent writes to the same record is a
   * race the model has no idea it created.
   */
  async executeAll(calls: ToolCall[], context: ToolExecutionContext): Promise<FunctionResult[]> {
    const results: FunctionResult[] = [];
    let batch: ToolCall[] = [];

    const flush = async () => {
      if (batch.length === 0) return;
      results.push(...(await Promise.all(batch.map((call) => this.execute(call, context)))));
      batch = [];
    };

    for (const call of calls) {
      const definition = this.functions.get(call.name);

      if (definition?.mutating) {
        // Everything queued so far completes first, then this runs alone.
        await flush();
        results.push(await this.execute(call, context));
        continue;
      }

      batch.push(call);
    }

    await flush();

    // Reordered to match the calls, because a model matching results to calls by position is a
    // model that will do so wrongly if the order changed.
    return calls.map(
      (call) =>
        results.find((result) => result.callId === call.id) ??
        this.failure(call, 'No result.', Date.now()),
    );
  }

  private failure(call: ToolCall, error: string, startedAt: number): FunctionResult {
    return {
      callId: call.id,
      name: call.name,
      ok: false,
      content: '',
      error,
      durationMs: Date.now() - startedAt,
    };
  }

  private async auditCall(
    call: ToolCall,
    context: ToolExecutionContext,
    definition: FunctionDefinition,
    ok: boolean,
    durationMs: number,
    error: string | null,
  ): Promise<void> {
    await this.options.audit?.record({
      action: ok ? 'agent.tool.executed' : 'agent.tool.failed',
      entityType: 'AiToolCall',
      entityId: call.id,
      actorId: context.actorId,
      organizationId: context.organizationId,
      after: {
        tool: definition.name,
        agentId: context.agentId ?? null,
        mutating: definition.mutating ?? false,
        permission: definition.permission ?? null,
        durationMs,
        error,
        /*
         * Arguments are recorded, and this is a deliberate exception to the "metadata not
         * content" rule elsewhere.
         *
         * A tool call is an *action*. "The agent called refund_order" without saying which order
         * is not an audit trail of anything. The arguments are the action.
         */
        arguments: truncate(call.arguments, 2000),
      },
    });
  }

  private async auditDenied(
    call: ToolCall,
    context: ToolExecutionContext,
    reason: string,
  ): Promise<void> {
    await this.options.audit?.record({
      action: 'agent.tool.denied',
      entityType: 'AiToolCall',
      entityId: call.id,
      actorId: context.actorId,
      organizationId: context.organizationId,
      after: {
        tool: call.name,
        agentId: context.agentId ?? null,
        reason,
        arguments: truncate(call.arguments, 2000),
      },
    });
  }

  /** For `trustos ai doctor` and the admin view. */
  describe(): Array<{
    name: string;
    description: string;
    permission: string | null;
    mutating: boolean;
    timeoutMs: number | null;
  }> {
    return [...this.functions.values()]
      .map((definition) => ({
        name: definition.name,
        description: definition.description,
        permission: definition.permission ?? null,
        mutating: definition.mutating ?? false,
        timeoutMs: definition.timeoutMs ?? null,
      }))
      .sort((a, b) => a.name.localeCompare(b.name));
  }

  names(): string[] {
    return [...this.functions.keys()].sort();
  }

  get size(): number {
    return this.functions.size;
  }
}

function truncate(value: string, max: number): string {
  return value.length > max ? `${value.slice(0, max)}… [truncated]` : value;
}
