// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * TrustOS Framework lint configuration.
 *
 * Beyond ordinary code quality, this config mechanically enforces the
 * dependency rules documented in docs/architecture.md. Violating a layering
 * rule is an error, not a style warning.
 */

const FRAMEWORK_PACKAGES = [
  '@trustsystem/audit',
  '@trustsystem/auth',
  '@trustsystem/config',
  '@trustsystem/database',
  '@trustsystem/errors',
  '@trustsystem/logging',
  '@trustsystem/api-keys',
  '@trustsystem/authorization',
  '@trustsystem/identity',
  '@trustsystem/module-registry',
  '@trustsystem/module-sdk',
  '@trustsystem/security-events',
  '@trustsystem/security-policy',
  '@trustsystem/security-testing',
  '@trustsystem/service-accounts',
  '@trustsystem/session-security',
  '@trustsystem/observability',
  '@trustsystem/rbac',
  '@trustsystem/shared-types',
  '@trustsystem/tenancy',
  '@trustsystem/validation',
];

/**
 * The modules the framework ships. Listed so the admin app cannot link against
 * one, and so a leaf package cannot depend on one.
 */
const MODULE_PACKAGES = [
  '@trustsystem/module-document',
  '@trustsystem/module-feature-flags',
  '@trustsystem/module-file-storage',
  '@trustsystem/module-notification',
  '@trustsystem/module-reporting',
  '@trustsystem/module-search',
  '@trustsystem/module-workflow',
];

/** Packages that must never be imported into browser-executed code. */
const SERVER_ONLY_PACKAGES = [
  '@trustsystem/config',
  '@trustsystem/database',
  '@trustsystem/auth',
  '@trustsystem/audit',
  '@trustsystem/logging',
  '@trustsystem/observability',
  '@trustsystem/tenancy',
  '@trustsystem/rbac',
  '@trustsystem/module-sdk',
  '@trustsystem/module-registry',
  '@trustsystem/identity',
  '@trustsystem/authorization',
  '@trustsystem/api-keys',
  '@trustsystem/service-accounts',
  '@trustsystem/session-security',
  '@trustsystem/security-events',
  '@trustsystem/security-policy',
];

const APP_PACKAGES = ['@trustsystem/api-example', '@trustsystem/admin-example', '@trustsystem/saas-starter'];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'packages/database/generated/**',
      // Generated by `next build` and rewritten on every run.
      'apps/*/next-env.d.ts',
      // Deliberately plain CommonJS: the bin shim has to run before anything
      // is compiled, so it cannot be an ES module or use TypeScript.
      'packages/cli/bin/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        // Node 20 web globals. `AbortController` is used by @trustsystem/retry's timeout handling and
        // by the smoke script; `performance` by the pilot's measurements.
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        performance: 'readonly',
        // Used by the validation scripts to build form-encoded token requests.
        URLSearchParams: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'off',
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../../*/src/*', '../../../*/src/*'],
              message:
                'Cross-package deep imports are forbidden. Import the package by name (e.g. "@trustsystem/errors").',
            },
          ],
          paths: APP_PACKAGES.map((name) => ({
            name,
            message: 'Applications must never be imported by other workspaces.',
          })),
        },
      ],
      eqeqeq: ['error', 'smart'],
      'no-console': 'warn',
    },
  },

  // --- Layer 0: leaf packages may not depend on any other framework package.
  {
    files: ['packages/shared-types/**/*.ts', 'packages/errors/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [...FRAMEWORK_PACKAGES, ...MODULE_PACKAGES]
            .filter((p) => p !== '@trustsystem/shared-types' && p !== '@trustsystem/errors')
            .map((name) => ({
              name,
              message:
                '@trustsystem/shared-types and @trustsystem/errors are leaf packages and must stay dependency-free.',
            })),
        },
      ],
    },
  },

  // --- Only @trustsystem/config may read process.env.
  {
    files: ['packages/**/*.ts'],
    ignores: [
      'packages/config/**/*.ts',
      'packages/**/*.spec.ts',
      'packages/**/*.test.ts',
      'packages/database/prisma/**/*.ts',
    ],
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message:
            'Read configuration through @trustsystem/config so every variable is validated exactly once.',
        },
      ],
    },
  },

  /*
   * The governance portal: browser code, served as static assets.
   *
   * Linted with Node's globals until this existed, so every `document`, `window` and
   * `sessionStorage` was reported as undefined — 23 errors that would have failed CI. It
   * is not TypeScript and not part of a workspace, so it needs its own entry rather than
   * inheriting one.
   */
  {
    files: ['apps/*/public/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        sessionStorage: 'readonly',
        localStorage: 'readonly',
        crypto: 'readonly',
        fetch: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        escape: 'readonly',
        TextEncoder: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      // The portal reports failures to whoever is looking at it, not to a log.
      'no-console': 'off',
    },
  },

  // --- Browser code must not link against server-only packages.
  {
    files: ['apps/admin-example/**/*.ts', 'apps/admin-example/**/*.tsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [...SERVER_ONLY_PACKAGES, ...MODULE_PACKAGES].map((name) => ({
            name,
            message:
              'Server-only package. The admin app may only use @trustsystem/shared-types and @trustsystem/errors.',
          })),
        },
      ],
      'no-console': 'off',
    },
  },

  // --- Scripts, seeds and tests get some slack.
  {
    files: [
      '**/*.spec.ts',
      '**/*.test.ts',
      '**/prisma/seed.ts',
      '**/scripts/**/*.ts',
      '**/*.config.ts',
      '**/*.config.mjs',
      '**/*.config.js',
    ],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-restricted-properties': 'off',
    },
  },
);
