// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * TrustOS Framework lint configuration.
 *
 * Beyond ordinary code quality, this config mechanically enforces the
 * dependency rules documented in docs/architecture.md. Violating a layering
 * rule is an error, not a style warning.
 */

const FRAMEWORK_PACKAGES = [
  '@trustos/audit',
  '@trustos/auth',
  '@trustos/config',
  '@trustos/database',
  '@trustos/errors',
  '@trustos/logging',
  '@trustos/observability',
  '@trustos/rbac',
  '@trustos/shared-types',
  '@trustos/tenancy',
  '@trustos/validation',
];

/** Packages that must never be imported into browser-executed code. */
const SERVER_ONLY_PACKAGES = [
  '@trustos/config',
  '@trustos/database',
  '@trustos/auth',
  '@trustos/audit',
  '@trustos/logging',
  '@trustos/observability',
  '@trustos/tenancy',
  '@trustos/rbac',
];

const APP_PACKAGES = ['@trustos/api-example', '@trustos/admin-example', '@trustos/saas-starter'];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'packages/database/generated/**',
      // Generated by `next build` and rewritten on every run.
      'apps/*/next-env.d.ts',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'off',
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../../*/src/*', '../../../*/src/*'],
              message:
                'Cross-package deep imports are forbidden. Import the package by name (e.g. "@trustos/errors").',
            },
          ],
          paths: APP_PACKAGES.map((name) => ({
            name,
            message: 'Applications must never be imported by other workspaces.',
          })),
        },
      ],
      eqeqeq: ['error', 'smart'],
      'no-console': 'warn',
    },
  },

  // --- Layer 0: leaf packages may not depend on any other framework package.
  {
    files: ['packages/shared-types/**/*.ts', 'packages/errors/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: FRAMEWORK_PACKAGES.filter(
            (p) => p !== '@trustos/shared-types' && p !== '@trustos/errors',
          ).map((name) => ({
            name,
            message:
              '@trustos/shared-types and @trustos/errors are leaf packages and must stay dependency-free.',
          })),
        },
      ],
    },
  },

  // --- Only @trustos/config may read process.env.
  {
    files: ['packages/**/*.ts'],
    ignores: [
      'packages/config/**/*.ts',
      'packages/**/*.spec.ts',
      'packages/**/*.test.ts',
      'packages/database/prisma/**/*.ts',
    ],
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message:
            'Read configuration through @trustos/config so every variable is validated exactly once.',
        },
      ],
    },
  },

  // --- Browser code must not link against server-only packages.
  {
    files: ['apps/admin-example/**/*.ts', 'apps/admin-example/**/*.tsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: SERVER_ONLY_PACKAGES.map((name) => ({
            name,
            message:
              'Server-only package. The admin app may only use @trustos/shared-types and @trustos/errors.',
          })),
        },
      ],
      'no-console': 'off',
    },
  },

  // --- Scripts, seeds and tests get some slack.
  {
    files: [
      '**/*.spec.ts',
      '**/*.test.ts',
      '**/prisma/seed.ts',
      '**/scripts/**/*.ts',
      '**/*.config.ts',
      '**/*.config.mjs',
      '**/*.config.js',
    ],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-restricted-properties': 'off',
    },
  },
);
