import { existsSync, readFileSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import {
  MODULE_CATALOG,
  isModuleRegistryError,
  requireModule,
  resolveInstallOrder,
  type ModuleCatalogEntry,
} from '@trustsystem/module-registry';
import {
  installedModuleIds,
  loadApplicationManifest,
  mergeApplicationManifest,
  type InstalledModule,
  type LoadedManifest,
} from './application-manifest';
import { GeneratorError } from './errors';
import { resolveWithin, toPosixPath } from './paths';
import {
  listFilesRecursively,
  normalizeLineEndings,
  type GenerationPlan,
  type PlannedFile,
} from './plan';
import {
  isManagedContent,
  mergeEnvExample,
  mergePackageJson,
  renderInstalledModulesFile,
  renderModuleConfigFile,
  renderModulesDoc,
} from './module-install-files';
import { applyPlan, type ApplyOptions, type ApplyResult } from './writer';

/**
 * Local module installation.
 *
 * The whole operation is plan-then-apply, like generation, and for the same
 * reason: `--dry-run` has to run the identical code path and stop before the
 * write, or it is not telling the truth.
 *
 * What makes installing into an *existing* project different from generating a new
 * one is that most of the target directory belongs to somebody else. Three rules
 * follow, and together they are the answer to "never overwrite custom code":
 *
 *   1. A file the installer does not own, that already exists, is a conflict. The
 *      run stops and names it.
 *   2. The files it does own carry a marker and are regenerated from the full
 *      installed set, so uninstalling later leaves nothing stale behind.
 *   3. `package.json`, `trustos.json` and `.env.example` are parsed and merged,
 *      never rewritten wholesale.
 *
 * The composition root — `app.module.ts`, with the guard order that is the
 * security model — is never touched.
 */

export interface InstallModuleRequest {
  /** Module ids to install. Dependencies are added automatically. */
  moduleIds: string[];
  /** Application root, containing `trustos.json`. */
  applicationRoot: string;
  /**
   * Framework checkout, used to find each module's `install/` payload and to
   * rewrite `@trustsystem/*` dependencies to `file:` links.
   */
  frameworkPath: string;
  /** Overrides the version recorded in the application manifest. */
  frameworkVersion?: string;
  /** Install optional dependencies too. Off by default. */
  includeOptional?: boolean;
  /** Explicit timestamp, so the same inputs produce identical output. */
  generatedAt?: string;
  /** Allow a module marked `deprecated`. */
  allowDeprecated?: boolean;
}

export interface InstallModulePlan {
  plan: GenerationPlan;
  applicationRoot: string;
  /** Modules that will be installed, dependency-first. */
  order: ModuleCatalogEntry[];
  /** Pulled in because something requested depends on them. */
  addedForDependencies: string[];
  /** Requested but already present. */
  alreadyInstalled: string[];
  /** Optional dependencies that were not installed. */
  skippedOptional: string[];
  /** Schema fragments written; each needs a migration. */
  migrations: string[];
  /** True when the application had no module-config file before this run. */
  createdModuleConfig: boolean;
  /**
   * True when `app.module.ts` already spreads `TRUSTOS_MODULE_IMPORTS`.
   *
   * Applications generated by this framework version do; one generated earlier
   * needs the line added by hand, and the installer says so rather than telling
   * everybody to check.
   */
  appModuleWired: boolean;
}

export interface InstallModuleResult extends ApplyResult {
  applicationRoot: string;
  installed: string[];
  alreadyInstalled: string[];
  addedForDependencies: string[];
  migrations: string[];
  nextSteps: string[];
}

const MODULES_DIRECTORY = 'apps/api/src/modules';
const INSTALLED_MODULES_FILE = `${MODULES_DIRECTORY}/trustos-modules.ts`;
const MODULE_CONFIG_FILE = `${MODULES_DIRECTORY}/module-config.ts`;
const MODULES_DOC_FILE = 'docs/modules.md';
const ENV_EXAMPLE_FILE = '.env.example';
const PACKAGE_JSON_FILE = 'package.json';

/** Files the installer is allowed to merge into rather than treat as conflicts. */
const MERGED_FILES = new Set([PACKAGE_JSON_FILE, ENV_EXAMPLE_FILE, 'trustos.json']);

/**
 * Builds the installation plan.
 *
 * Everything that can fail — an unknown module, an incompatible framework, a
 * conflicting file, a missing payload — fails here, before anything is written.
 */
export async function planModuleInstall(request: InstallModuleRequest): Promise<InstallModulePlan> {
  const applicationRoot = resolve(request.applicationRoot);
  const loaded = await loadApplicationManifest(applicationRoot);
  const frameworkVersion = request.frameworkVersion ?? loaded.manifest.frameworkVersion;

  if (!loaded.manifest.generated.api) {
    throw new GeneratorError(
      'invalid_input',
      'This application was generated without an API, so there is nowhere to mount a module.',
      'Modules expose HTTP routes and need apps/api.',
    );
  }

  const already = installedModuleIds(loaded.manifest);

  let resolved;
  try {
    resolved = resolveInstallOrder(MODULE_CATALOG, request.moduleIds, {
      frameworkVersion,
      installed: already,
      ...(request.includeOptional === undefined
        ? {}
        : { includeOptional: request.includeOptional }),
    });
  } catch (error) {
    // The registry's failures are the installer's failures, translated so the CLI
    // has one error type to report.
    if (isModuleRegistryError(error)) {
      throw new GeneratorError('invalid_input', error.message, error.hint);
    }
    throw error;
  }

  if (!request.allowDeprecated) {
    const deprecated = resolved.order.filter((entry) => entry.metadata.stability === 'deprecated');
    if (deprecated.length > 0) {
      throw new GeneratorError(
        'invalid_input',
        `Deprecated module(s): ${deprecated.map((entry) => entry.metadata.id).join(', ')}.`,
        'Pass --force to install one anyway.',
      );
    }
  }

  const generatedAt = request.generatedAt ?? new Date().toISOString();

  // The full set after this run: what was there plus what is being added. Managed
  // files are regenerated from this, never appended to.
  const installedAfter: InstalledModule[] = [
    ...loaded.manifest.modules,
    ...resolved.order.map((entry) => ({
      id: entry.metadata.id,
      version: entry.metadata.version,
      installedAt: generatedAt,
      installedAsDependency: resolved.addedForDependencies.includes(entry.metadata.id),
    })),
  ];

  const allEntries = installedAfter.map((module) => requireModule(module.id));

  const files: PlannedFile[] = [];
  const migrations: string[] = [];

  // --- each module's own payload -------------------------------------------
  for (const entry of resolved.order) {
    for (const file of await collectPayload(request.frameworkPath, entry, applicationRoot)) {
      files.push(file);
      if (file.path.startsWith('prisma/schema/')) migrations.push(file.path);
    }
  }

  // --- managed wiring -------------------------------------------------------
  files.push(
    await plannedFile(
      applicationRoot,
      INSTALLED_MODULES_FILE,
      renderInstalledModulesFile(allEntries),
      {
        managed: true,
        source: 'installer',
      },
    ),
  );

  // --- created once ---------------------------------------------------------
  const moduleConfigPath = resolveWithin(applicationRoot, MODULE_CONFIG_FILE);
  const createdModuleConfig = !existsSync(moduleConfigPath);

  if (createdModuleConfig) {
    files.push(
      await plannedFile(applicationRoot, MODULE_CONFIG_FILE, renderModuleConfigFile(allEntries), {
        source: 'installer',
      }),
    );
  }

  // --- managed documentation ------------------------------------------------
  files.push(
    await plannedFile(
      applicationRoot,
      MODULES_DOC_FILE,
      renderModulesDoc(allEntries, {
        applicationName: loaded.manifest.application.displayName,
        frameworkVersion,
      }),
      { managed: true, source: 'installer' },
    ),
  );

  // --- merged files ---------------------------------------------------------
  files.push(
    await mergedFile(applicationRoot, PACKAGE_JSON_FILE, (current) =>
      mergePackageJson(current, moduleDependencies(resolved.order, request.frameworkPath)),
    ),
  );

  files.push(
    await mergedFile(applicationRoot, ENV_EXAMPLE_FILE, (current) =>
      mergeEnvExample(current, resolved.order),
    ),
  );

  files.push(
    await plannedFile(
      applicationRoot,
      'trustos.json',
      mergeApplicationManifest(loaded, installedAfter),
      { managed: true, source: 'installer' },
    ),
  );

  assertNoUnownedOverwrites(files, applicationRoot, loaded);
  await assertNoPrismaModelCollisions(files, applicationRoot, resolved.order);

  return {
    plan: {
      projectRoot: applicationRoot,
      files: files.sort((left, right) => (left.path < right.path ? -1 : 1)),
      overrides: [],
    },
    applicationRoot,
    order: resolved.order,
    addedForDependencies: resolved.addedForDependencies,
    alreadyInstalled: resolved.alreadyInstalled,
    skippedOptional: resolved.skippedOptional,
    migrations,
    createdModuleConfig,
    appModuleWired: appModuleSpreadsImports(applicationRoot),
  };
}

/**
 * Whether the composition root already spreads the installed-module list.
 *
 * A text check rather than a parse, and that is the right level: the installer
 * never edits this file, so all it needs to know is whether to print an
 * instruction.
 */
function appModuleSpreadsImports(applicationRoot: string): boolean {
  const path = join(applicationRoot, 'apps', 'api', 'src', 'app.module.ts');
  const contents = readFileSyncSafe(path);
  return contents !== null && contents.includes('TRUSTOS_MODULE_IMPORTS');
}

/** Plans and applies. */
export async function installModules(
  request: InstallModuleRequest,
  options: ApplyOptions = {},
): Promise<InstallModuleResult> {
  const planned = await planModuleInstall(request);

  // `force: true` here means "managed files may be rewritten", which `applyPlan`
  // already permits on its own; the flag covers the merged files, whose conflict
  // check happened in `assertNoUnownedOverwrites` with far more context than the
  // writer has.
  const result = await applyPlan(planned.plan, { ...options, force: true });

  return {
    ...result,
    applicationRoot: planned.applicationRoot,
    installed: planned.order.map((entry) => entry.metadata.id),
    alreadyInstalled: planned.alreadyInstalled,
    addedForDependencies: planned.addedForDependencies,
    migrations: planned.migrations,
    nextSteps: nextStepsFor(planned),
  };
}

/** What a developer does after a successful install, in order. */
export function nextStepsFor(planned: InstallModulePlan): string[] {
  const steps: string[] = ['npm install'];

  if (planned.migrations.length > 0) {
    steps.push('npm run db:migrate    # applies the module schema fragments');
  }

  if (!planned.appModuleWired) {
    steps.push('Add ...TRUSTOS_MODULE_IMPORTS to the imports array in apps/api/src/app.module.ts');
  }

  steps.push('Seed TRUSTOS_MODULE_PERMISSIONS onto roles in prisma/seed.ts', 'npm test');

  if (planned.createdModuleConfig) {
    steps.push('Optional: set module configuration in apps/api/src/modules/module-config.ts');
  }

  return steps;
}

// ---------------------------------------------------------------------------

/**
 * Packages the module system itself needs in a host application.
 *
 * The SDK is here because the generated wiring imports `@trustsystem/module-sdk/nest`,
 * and the registry because a module reads its own declarations from the catalog.
 * They are added explicitly rather than relied on as transitive dependencies: npm
 * links a `file:` dependency but does not install that package's own unpublished
 * `@trustsystem/*` requirements, so a transitive-only assumption leaves the application
 * unable to resolve the import — which is a `tsc` error at build time and a boot
 * failure at run time.
 */
const MODULE_SYSTEM_PACKAGES = [
  { name: '@trustsystem/module-sdk', directory: 'packages/module-sdk' },
  { name: '@trustsystem/module-registry', directory: 'packages/module-registry' },
];

/** Dependency specifiers for the module packages being installed. */
export function moduleDependencies(
  entries: ModuleCatalogEntry[],
  frameworkPath: string,
): Record<string, string> {
  const additions: Record<string, string> = {};
  const root = resolve(frameworkPath);

  // `file:` while the packages are unpublished, exactly as generation does for the
  // framework packages.
  for (const { name, directory } of MODULE_SYSTEM_PACKAGES) {
    additions[name] = `file:${join(root, directory)}`;
  }

  for (const entry of entries) {
    additions[entry.packaging.packageName] = `file:${join(root, entry.packaging.directory)}`;
  }

  return additions;
}

/**
 * Reads a module's `install/` tree.
 *
 * Every destination path is contained with `resolveWithin`, on every file — a
 * payload path is the one input here that could escape the application directory.
 */
async function collectPayload(
  frameworkPath: string,
  entry: ModuleCatalogEntry,
  applicationRoot: string,
): Promise<PlannedFile[]> {
  const payloadRoot = join(resolve(frameworkPath), entry.packaging.directory, 'install');

  // A module with no payload is legitimate: search owns no tables and adds no
  // application files.
  if (!existsSync(payloadRoot)) return [];

  const files: PlannedFile[] = [];

  for (const relative of await listFilesRecursively(payloadRoot)) {
    const target = toPosixPath(relative);
    const contents = await readFile(join(payloadRoot, relative), 'utf8');

    files.push(
      await plannedFile(applicationRoot, target, contents, {
        source: entry.metadata.id,
        // A schema fragment is owned by the module: reinstalling must be able to
        // refresh it, and it is not a file anybody should be editing by hand.
        managed: true,
      }),
    );
  }

  return files;
}

async function plannedFile(
  applicationRoot: string,
  path: string,
  contents: string,
  options: { managed?: boolean; source: string },
): Promise<PlannedFile> {
  const absolutePath = resolveWithin(applicationRoot, path);

  return {
    path,
    absolutePath,
    contents: normalizeLineEndings(contents),
    rendered: true,
    exists: existsSync(absolutePath),
    source: options.source,
    ...(options.managed ? { managed: true } : {}),
  };
}

/** A file that must already exist and is transformed rather than replaced. */
async function mergedFile(
  applicationRoot: string,
  path: string,
  transform: (current: string) => string,
): Promise<PlannedFile> {
  const absolutePath = resolveWithin(applicationRoot, path);

  if (!existsSync(absolutePath)) {
    throw new GeneratorError(
      'invalid_input',
      `${path} is missing from ${applicationRoot}.`,
      'This does not look like a complete generated application.',
    );
  }

  return {
    path,
    absolutePath,
    contents: normalizeLineEndings(transform(await readFile(absolutePath, 'utf8'))),
    rendered: true,
    exists: true,
    source: 'installer',
    managed: true,
  };
}

/**
 * Refuses to overwrite anything the installer does not own.
 *
 * The check is on the *content* of the file on disk, not on its path: a path could
 * match by accident, while the marker is only there if a previous install put it
 * there. A file that exists, is not a merge target, and has no marker, is somebody's
 * code — and the run stops rather than replacing it.
 */
/** `model Foo {` and `enum Foo {` at the start of a line. */
const PRISMA_DECLARATION = /^\s*(?:model|enum)\s+(\w+)\s*\{/gm;

function declaredPrismaTypes(contents: string): string[] {
  return [...contents.matchAll(PRISMA_DECLARATION)].map((match) => match[1] as string);
}

/**
 * Refuses an install whose Prisma fragment redefines a model the application already has.
 *
 * Prisma merges every file in `prisma/schema/` into one schema, so two files declaring
 * `model WorkflowDefinition` is not an override — it is a schema that will not compile.
 * Without this check the installer writes the fragment happily and the application only
 * breaks later, at `prisma generate`, with an error naming a file the developer did not
 * write. Templates that build their own richer version of a module's domain are the
 * normal way to hit this, and the fix is a decision (use the template's, or the
 * module's) rather than something the installer can make on someone's behalf.
 */
async function assertNoPrismaModelCollisions(
  files: PlannedFile[],
  applicationRoot: string,
  installing: ModuleCatalogEntry[],
): Promise<void> {
  const planned = files.filter(
    (file) => file.path.startsWith('prisma/schema/') && file.path.endsWith('.prisma'),
  );
  if (planned.length === 0) return;

  const schemaDirectory = resolveWithin(applicationRoot, 'prisma/schema');
  if (!existsSync(schemaDirectory)) return;

  // A fragment the installer is itself writing is not competing with itself.
  const plannedPaths = new Set(planned.map((file) => file.path));
  const owners = new Map<string, string>();

  for (const name of await readdir(schemaDirectory)) {
    if (!name.endsWith('.prisma')) continue;

    const relative = `prisma/schema/${name}`;
    if (plannedPaths.has(relative)) continue;

    const contents = await readFile(join(schemaDirectory, name), 'utf8');
    for (const type of declaredPrismaTypes(contents)) owners.set(type, relative);
  }

  const collisions: { type: string; fragment: string; existing: string }[] = [];

  for (const file of planned) {
    for (const type of declaredPrismaTypes(file.contents)) {
      const existing = owners.get(type);
      if (existing) collisions.push({ type, fragment: file.path, existing });
    }
  }

  if (collisions.length === 0) return;

  const detail = collisions
    .map((clash) => `  ${clash.type}: ${clash.fragment} would redefine ${clash.existing}`)
    .join('\n');

  throw new GeneratorError(
    'invalid_input',
    `Installing ${installing.map((entry) => entry.metadata.id).join(', ')} would define ${collisions.length === 1 ? 'a model that' : 'models that'} the application already defines:\n${detail}`,
    'This application already implements that domain. Either keep its own schema and do not install the module, or remove the existing fragment first.',
  );
}

function assertNoUnownedOverwrites(
  files: PlannedFile[],
  applicationRoot: string,
  loaded: LoadedManifest,
): void {
  const problems: string[] = [];

  for (const file of files) {
    if (!file.exists) continue;
    if (MERGED_FILES.has(file.path)) continue;

    const current = readFileSyncSafe(file.absolutePath);
    if (current !== null && isManagedContent(current)) continue;

    problems.push(file.path);
  }

  if (problems.length === 0) return;

  throw new GeneratorError(
    'target_not_empty',
    `Refusing to overwrite ${problems.length} file(s) the installer does not own: ${problems.join(', ')}.`,
    `Move or delete them, or install into a clean checkout. ${
      loaded.manifest.modules.length > 0
        ? 'A previous install would have left the marker comment in place; its absence means the file was edited.'
        : 'These files predate any module installation.'
    }`,
  );
}

function readFileSyncSafe(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

/** Locates the framework checkout from the module packages' directory. */
export function resolveFrameworkPath(startDirectory: string = __dirname): string {
  let current = resolve(startDirectory);

  for (let depth = 0; depth < 10; depth += 1) {
    if (existsSync(join(current, 'packages', 'modules'))) return current;

    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }

  throw new GeneratorError(
    'template_not_found',
    'Could not locate the framework checkout.',
    'Run the CLI from a TrustOS framework checkout, or pass --framework-path.',
  );
}
