import type { ModuleCatalogEntry } from '@trustsystem/module-registry';
import { GeneratorError } from './errors';
import { normalizeLineEndings } from './plan';

/**
 * The files `trustos add-module` writes, other than a module's own payload.
 *
 * Two kinds, and the difference is the whole safety story of the installer:
 *
 *   * **Managed files** carry `MANAGED_MARKER` and are regenerated from the full
 *     installed set on every run. The installer owns them outright, so it can
 *     rewrite them without asking — and because it regenerates from the whole set
 *     rather than appending, removing a module later leaves nothing behind.
 *
 *   * **Merged files** — `package.json`, `trustos.json`, `.env.example` — already
 *     belong to the application. They are parsed, changed in one specific way, and
 *     written back with everything else intact.
 *
 * Anything that is neither, and already exists, is a conflict the installer
 * refuses. There is no path by which it overwrites hand-written code.
 */

export const MANAGED_MARKER = 'trustos:managed-file';

const TS_MARKER = `// ${MANAGED_MARKER} — generated by \`trustos add-module\`. Edits are overwritten.`;
const MD_MARKER = `<!-- ${MANAGED_MARKER} — generated by \`trustos add-module\`. Edits are overwritten. -->`;

/** True when a file on disk is one the installer owns. */
export function isManagedContent(contents: string): boolean {
  return contents.includes(MANAGED_MARKER);
}

/** A TypeScript string literal. Only ever applied to catalog-derived values. */
function literal(value: string): string {
  return JSON.stringify(value);
}

/**
 * `apps/api/src/modules/trustos-modules.ts`.
 *
 * The single point where installed modules meet the application. `app.module.ts`
 * spreads `TRUSTOS_MODULE_IMPORTS` and is never touched by the installer, which is
 * what keeps the composition root — and the guard order inside it — under human
 * control.
 */
export function renderInstalledModulesFile(entries: ModuleCatalogEntry[]): string {
  const sorted = [...entries].sort((left, right) =>
    left.metadata.id < right.metadata.id ? -1 : 1,
  );

  const imports = sorted
    .map(
      (entry) =>
        `import { ${entry.packaging.nestModule.className} } from ${literal(
          entry.packaging.nestModule.importPath,
        )};`,
    )
    .join('\n');

  const registrations = sorted
    .map(
      (entry) =>
        `  ${entry.packaging.nestModule.className}.forRoot(binding(${literal(
          entry.metadata.id,
        )})),`,
    )
    .join('\n');

  const permissions = sorted
    .flatMap((entry) => entry.permissions.map((permission) => `  ${literal(permission.key)},`))
    .join('\n');

  const body = `${TS_MARKER}
/**
 * Installed TrustOS modules.
 *
 * Regenerated by \`trustos add-module\` from the full installed set. Do not edit:
 * put per-module configuration in \`module-config.ts\`, which the installer creates
 * once and never rewrites.
 *
 * \`AppModule\` spreads \`TRUSTOS_MODULE_IMPORTS\` into its imports. The installer
 * does not touch \`app.module.ts\`, so the guard order that makes up the security
 * model stays under human control.
 */
import type { DynamicModule } from '@nestjs/common';
import type { AppConfig } from '@trustsystem/config';
import type { AuditService } from '@trustsystem/audit';
import { PrismaService } from '@trustsystem/database';
import type { Logger } from '@trustsystem/logging';
import type { ModuleHostBinding } from '@trustsystem/module-sdk/nest';
${imports}
import { APP_CONFIG_TOKEN, APP_LOGGER, AUDIT_SERVICE } from '../tokens';
import { MODULE_CONFIG, type InstalledModuleId } from './module-config';

/**
 * Where each module finds its logger, audit service, database client and
 * configuration.
 *
 * The tokens are this application's own, exported by the global \`AppModule\`; a
 * module never depends on a host having adopted a particular token name.
 */
function binding(moduleId: InstalledModuleId): ModuleHostBinding {
  return {
    inject: [APP_LOGGER, AUDIT_SERVICE, PrismaService, APP_CONFIG_TOKEN],
    useFactory: ((logger: Logger, audit: AuditService, prisma: PrismaService, config: AppConfig) => ({
      logger,
      audit,
      prisma,
      environment: config.env,
      config: MODULE_CONFIG[moduleId],
    })) as ModuleHostBinding['useFactory'],
  };
}

/** Add to \`AppModule.forRoot\`: \`imports: [..., ...TRUSTOS_MODULE_IMPORTS]\`. */
export const TRUSTOS_MODULE_IMPORTS: DynamicModule[] = [
${registrations}
];

/**
 * Permissions the installed modules introduce.
 *
 * Nothing grants these — a module that could grant its own permissions would be a
 * privilege-escalation path. Seed them onto roles in \`prisma/seed.ts\`, using each
 * module's suggested roles in \`docs/modules.md\` as a starting point.
 */
export const TRUSTOS_MODULE_PERMISSIONS: string[] = [
${permissions}
];
`;

  return normalizeLineEndings(body);
}

/**
 * `apps/api/src/modules/module-config.ts`.
 *
 * Created once and never rewritten, because it is where an application puts its
 * own settings. New modules are added to it by hand — the installer prints the
 * line — which is the trade for it being a file a developer owns.
 */
export function renderModuleConfigFile(entries: ModuleCatalogEntry[]): string {
  const ids = [...entries]
    .map((entry) => entry.metadata.id)
    .sort()
    .map((id) => `  ${literal(id)}: {},`)
    .join('\n');

  const body = `/**
 * Per-module configuration.
 *
 * Created once by \`trustos add-module\` and yours from then on: the installer never
 * rewrites this file. Every module accepts \`{}\` and starts with safe defaults, so
 * filling it in is optional.
 *
 * Each module validates its own configuration with a Zod schema when the
 * application starts, so a wrong value fails at boot rather than when a customer
 * reaches the code path that reads it. See \`docs/modules.md\` for what each module
 * accepts, and for the environment variables it reads.
 *
 * Per-organization overrides are a different mechanism: they live in the module's
 * tenant settings, not here. This object is the application-wide default.
 */
export const MODULE_CONFIG = {
${ids}
} satisfies Record<string, Record<string, unknown>>;

export type InstalledModuleId = keyof typeof MODULE_CONFIG;
`;

  return normalizeLineEndings(body);
}

/**
 * `docs/modules.md`.
 *
 * Managed, and regenerated from the installed set. Generated documentation that
 * lists permissions and routes is worth more than hand-written prose here, because
 * the hand-written version is the one that goes stale the first time a module is
 * upgraded.
 */
export function renderModulesDoc(
  entries: ModuleCatalogEntry[],
  options: { applicationName: string; frameworkVersion: string },
): string {
  const sorted = [...entries].sort((left, right) =>
    left.metadata.id < right.metadata.id ? -1 : 1,
  );

  const sections = sorted.map((entry) => {
    const permissions = entry.permissions
      .map(
        (permission) =>
          `| \`${permission.key}\` | ${permission.description} | ${
            permission.suggestedRoles.join(', ') || '—'
          } |`,
      )
      .join('\n');

    const routes = entry.routes
      .map(
        (route) =>
          `| \`${route.method} ${route.path}\` | \`${route.permission}\` | ${route.summary} |`,
      )
      .join('\n');

    const environment = entry.environment.length
      ? entry.environment
          .map((variable) => `- \`${variable.name}\` — ${variable.description}`)
          .join('\n')
      : '_None._';

    const flags = entry.featureFlags.length
      ? entry.featureFlags
          .map(
            (flag) =>
              `- \`${flag.key}\` (default ${flag.defaultValue ? 'on' : 'off'}) — ${flag.description}`,
          )
          .join('\n')
      : '_None._';

    const migrations = entry.migrations.length
      ? entry.migrations
          .map((migration) => `- \`${migration.schemaFragment}\` — ${migration.description}`)
          .join('\n')
      : '_None. This module owns no tables._';

    const extensions = entry.extensionPoints
      .map(
        (point) =>
          `- **${point.name}** (\`${point.port}\`) — ${point.description} Ships: ${
            point.provided.map((name) => `\`${name}\``).join(', ') || '—'
          }.`,
      )
      .join('\n');

    const dependencies = entry.dependencies.length
      ? entry.dependencies
          .map(
            (dependency) =>
              `- \`${dependency.moduleId}\` ${dependency.versionRange} — ${dependency.reason}`,
          )
          .join('\n')
      : '_None._';

    return `## ${entry.metadata.name}

\`${entry.metadata.id}\` v${entry.metadata.version} · ${entry.metadata.stability} · owned by ${entry.metadata.owner}

${entry.metadata.description}

### Permissions

| Key | Description | Suggested roles |
| --- | --- | --- |
${permissions}

### Routes

| Route | Permission | Summary |
| --- | --- | --- |
${routes}

### Configuration

Application-wide defaults go in \`apps/api/src/modules/module-config.ts\`. Every
value has a safe default, so the module works with none.

Environment variables:

${environment}

### Feature flags

${flags}

### Database

${migrations}

### Extension points

${extensions}

### Depends on

${dependencies}

### Out of scope

${entry.outOfScope.map((item) => `- ${item}`).join('\n')}
`;
  });

  const summary = sorted
    .map(
      (entry) =>
        `| [${entry.metadata.name}](#${entry.metadata.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}) | \`${entry.metadata.id}\` | ${entry.metadata.version} | ${entry.routes.length} | ${entry.permissions.length} |`,
    )
    .join('\n');

  const body = `${MD_MARKER}

# Installed modules — ${options.applicationName}

Framework ${options.frameworkVersion}. Regenerated by \`trustos add-module\`; edits
are overwritten.

${
  sorted.length === 0
    ? 'No modules are installed. Run `trustos add-module <id>` to add one.'
    : `| Module | Id | Version | Routes | Permissions |
| --- | --- | --- | --- | --- |
${summary}`
}

## After installing

1. \`npm install\` — link the module packages.
2. \`npm run db:migrate\` — apply the schema fragments listed below.
3. Seed the permissions onto roles. \`TRUSTOS_MODULE_PERMISSIONS\` in
   \`apps/api/src/modules/trustos-modules.ts\` is the full list.
4. \`npm test\` — the tenant-isolation suites run against the merged schema.

Nothing grants a module's permissions automatically. A module that could grant its
own permissions would be a privilege-escalation path in a package, so the decision
stays with the application's seed.

${sections.join('\n')}`;

  return normalizeLineEndings(body);
}

/**
 * `package.json`, with the module packages added to `dependencies`.
 *
 * Parsed and rewritten rather than patched textually, and every other field is
 * left exactly as it was. Key order inside `dependencies` is sorted, which is what
 * npm itself does on install — so the file does not churn on every run.
 */
export function mergePackageJson(
  currentContents: string,
  additions: Record<string, string>,
): string {
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(currentContents) as Record<string, unknown>;
  } catch (error) {
    throw new GeneratorError(
      'invalid_input',
      `package.json is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const dependencies = {
    ...((parsed.dependencies as Record<string, string> | undefined) ?? {}),
    ...additions,
  };

  const merged = {
    ...parsed,
    dependencies: Object.fromEntries(
      Object.entries(dependencies).sort(([left], [right]) => (left < right ? -1 : 1)),
    ),
  };

  return normalizeLineEndings(JSON.stringify(merged, null, 2));
}

const ENV_BLOCK_START = (id: string) => `# >>> trustos module: ${id}`;
const ENV_BLOCK_END = (id: string) => `# <<< trustos module: ${id}`;

/**
 * `.env.example`, with one anchored block per module.
 *
 * Anchored so a second run replaces a module's block rather than appending a
 * duplicate, and so anything the developer wrote outside the anchors is untouched.
 *
 * Only variable *names* are written, never values. A module cannot contribute a
 * value here, so it cannot contribute a secret-shaped default that someone later
 * fills in and commits — and `.env.example` is the only environment file the
 * generator will produce at all.
 */
export function mergeEnvExample(currentContents: string, entries: ModuleCatalogEntry[]): string {
  let output = currentContents.replace(/\r\n/g, '\n');

  for (const entry of [...entries].sort((left, right) =>
    left.metadata.id < right.metadata.id ? -1 : 1,
  )) {
    if (entry.environment.length === 0) continue;

    const id = entry.metadata.id;
    const lines = [
      ENV_BLOCK_START(id),
      `# ${entry.metadata.name} module. Every variable is optional: the module has`,
      '# safe defaults and validates whatever is set when the application starts.',
      ...entry.environment.flatMap((variable) => [
        `# ${variable.description}`,
        `${variable.name}=`,
      ]),
      ENV_BLOCK_END(id),
    ].join('\n');

    const existing = new RegExp(
      `${escapeRegExp(ENV_BLOCK_START(id))}[\\s\\S]*?${escapeRegExp(ENV_BLOCK_END(id))}`,
    );

    output = existing.test(output)
      ? output.replace(existing, lines)
      : `${output.replace(/\n+$/, '')}\n\n${lines}\n`;
  }

  return normalizeLineEndings(output);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
