import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The template copies of the framework schema must match the framework.
 *
 * Prisma has no cross-package schema import, so a generated application carries its own copy of
 * the framework models. A hand-maintained copy drifts *silently*: a client generated from a
 * stale schema does not know a column, and the first symptom is a runtime error rather than a
 * build failure.
 *
 * That is why this test exists. The base template's copy sat at 9 models while the framework had
 * 27 — so `ApiKey`, `ServiceAccount`, `UserSession` and `SecurityEvent` were unreachable from
 * every generated application for two phases, and nothing noticed.
 *
 * The fragments are now generated by `scripts/sync-schema-fragments.mjs`. This asserts they are
 * what that script would produce.
 */

const ROOT = join(__dirname, '..', '..', '..');

async function expected(): Promise<Array<{ path: string; content: string }>> {
  // Imported dynamically because the script is ESM and this suite is not built through the
  // project references — the alternative is duplicating the extraction here, which would mean a
  // test that passes against its own copy of the bug.
  const module = (await import(
    join(ROOT, 'scripts', 'sync-schema-fragments.mjs')
  )) as typeof import('../../../scripts/sync-schema-fragments.mjs');

  return module.expectedFragments();
}

describe('the template schema fragments', () => {
  it('are byte-identical to what the sync script produces', async () => {
    const fragments = await expected();
    expect(fragments.length).toBeGreaterThan(0);

    for (const fragment of fragments) {
      const actual = readFileSync(join(ROOT, fragment.path), 'utf8');

      expect(
        actual === fragment.content,
        `${fragment.path} has drifted from the framework schema.\n` +
          'Run: node scripts/sync-schema-fragments.mjs',
      ).toBe(true);
    }
  });

  it('together cover every model in the framework schema', async () => {
    const source = readFileSync(
      join(ROOT, 'packages', 'database', 'prisma', 'schema.prisma'),
      'utf8',
    );

    const modelsIn = (schema: string) =>
      new Set([...schema.matchAll(/^model\s+(\w+)\s*\{/gm)].map((match) => match[1] as string));

    const framework = modelsIn(source);
    const covered = new Set<string>();

    for (const fragment of await expected()) {
      for (const model of modelsIn(fragment.content)) covered.add(model);
    }

    const missing = [...framework].filter((model) => !covered.has(model)).sort();

    /*
     * The assertion that would have caught the original drift.
     *
     * A model in the framework schema that no fragment carries is a table a generated
     * application cannot see — and the framework code that writes to it will fail at runtime
     * with "property does not exist on PrismaService".
     */
    expect(
      missing,
      `Framework models carried by no template fragment: ${missing.join(', ')}. ` +
        'Add them to a fragment in scripts/sync-schema-fragments.mjs.',
    ).toEqual([]);
  });

  it('carry the identity and security models in the base fragment', async () => {
    const [base] = await expected();

    // Every application needs these, so they belong in `_base` rather than in a template that
    // opts in. Naming them explicitly rather than counting, because a count passes when one
    // model is swapped for another.
    for (const model of [
      'User',
      'Organization',
      'OrganizationMember',
      'Role',
      'Permission',
      'RefreshToken',
      'AuditLog',
      'SecurityEvent',
      'ApiKey',
      'ServiceAccount',
      'UserSession',
    ]) {
      expect(base?.content, model).toContain(`model ${model} {`);
    }
  });

  it('keeps the workflow models out of the base fragment', async () => {
    const [base] = await expected();

    // Fourteen unused tables in every generated application would be fourteen tables somebody
    // has to explain — and a migration that creates them for an app that will never use them.
    expect(base?.content).not.toContain('model WorkflowInstance {');
    expect(base?.content).not.toContain('model CaseRecord {');
  });

  it('gives the generated client an explicit output path', async () => {
    const [base] = await expected();

    /*
     * The framework's own generator block has no `output`, so its client lands in
     * `node_modules/@prisma/client`. A generated application must not: the framework packages
     * are linked from a checkout with its own client generated from the framework schema alone,
     * and sharing the default location makes which one wins a function of npm hoisting — the
     * loser being a client that has never heard of the product's models.
     *
     * The first version of the sync script copied the block verbatim and produced a generated
     * application whose typecheck failed with "cannot find module ../generated/client". This is
     * the assertion that catches it.
     */
    expect(base?.content).toContain('output   = "../generated/client"');
  });

  it('declares the generator and datasource exactly once, in the base fragment', async () => {
    const fragments = await expected();

    const declaring = fragments.filter((fragment) => fragment.content.includes('datasource db {'));
    // Prisma loads every file in the directory and refuses two datasource blocks, so this is a
    // generated application that fails `prisma validate` rather than one that misbehaves later.
    expect(declaring).toHaveLength(1);
    expect(declaring[0]?.path).toContain('_base');
  });
});
