// trustos:managed-file — generated by `trustos add-module`. Edits are overwritten.
/**
 * Installed TrustOS modules.
 *
 * Empty until `trustos add-module` is run, at which point this file is regenerated
 * from the full installed set. It carries the marker above from the start, so the
 * installer knows it owns the file and does not treat it as hand-written code.
 *
 * `AppModule` spreads `TRUSTOS_MODULE_IMPORTS` into its imports. The installer does
 * not touch `app.module.ts`, so the guard order that makes up the security model
 * stays under human control.
 */
import type { DynamicModule } from '@nestjs/common';

/** Spread into `AppModule.forRoot`. */
export const TRUSTOS_MODULE_IMPORTS: DynamicModule[] = [];

/**
 * Permissions the installed modules introduce.
 *
 * Nothing grants these — a module that could grant its own permissions would be a
 * privilege-escalation path. Seed them onto roles in `prisma/seed.ts`.
 */
export const TRUSTOS_MODULE_PERMISSIONS: string[] = [];
