#!/usr/bin/env node
/**
 * Computes the pilot's framework reuse from the repository, not from an estimate.
 *
 * Two figures, because one alone misleads.
 *
 * The **line ratio** counts source lines in the transitive closure of framework packages the
 * pilot's runtime code imports, against the pilot's own lines. It is honest about the payment
 * path and says nothing about the enterprise layer, which the pilot *configures* rather than
 * imports at runtime.
 *
 * The **capability table** is the one the specification asks for: for each capability the
 * application needs, which TrustOS module provides it, and how much pilot code sits beside it.
 * That table is the answer to "did we rebuild anything", and a line count cannot be.
 *
 * Run: node scripts/pilot-reuse.mjs
 */
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const PILOT = 'apps/merchant-wallet-basic/src';

function walk(dir, filter) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry === 'node_modules' || entry === 'dist') continue;
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) out.push(...walk(path, filter));
    else if (filter(entry)) out.push(path);
  }
  return out;
}

const lineCount = (paths) =>
  paths.reduce((total, path) => total + readFileSync(path, 'utf8').split('\n').length, 0);

const isSource = (name) => name.endsWith('.ts') && !name.endsWith('.spec.ts');
const isSpec = (name) => name.endsWith('.spec.ts');

const pilotSource = walk(PILOT, isSource);
const pilotSpec = walk(PILOT, isSpec);

/** Packages the pilot's runtime code imports directly. */
const direct = new Set();
for (const path of pilotSource) {
  for (const match of readFileSync(path, 'utf8').matchAll(/@trustos\/([a-z-]+)/g)) {
    direct.add(match[1]);
  }
}

/** Packages the pilot's tests configure but its runtime does not import. */
const configured = new Set();
for (const path of pilotSpec) {
  for (const match of readFileSync(path, 'utf8').matchAll(/@trustos\/([a-z-]+)/g)) {
    if (!direct.has(match[1])) configured.add(match[1]);
  }
}

/** The transitive closure of a set of packages. */
function closure(roots) {
  const seen = new Set();
  const queue = [...roots];

  while (queue.length > 0) {
    const name = queue.pop();
    if (seen.has(name)) continue;
    seen.add(name);

    let manifest;
    try {
      manifest = JSON.parse(readFileSync(`packages/${name}/package.json`, 'utf8'));
    } catch {
      continue;
    }

    for (const dependency of Object.keys(manifest.dependencies ?? {})) {
      if (dependency.startsWith('@trustos/')) queue.push(dependency.slice('@trustos/'.length));
    }
  }

  return seen;
}

const runtimeClosure = closure(direct);
const withConfigured = closure([...direct, ...configured]);

const linesOf = (names) => {
  const detail = {};
  let total = 0;
  for (const name of [...names].sort()) {
    const count = lineCount(walk(`packages/${name}/src`, isSource));
    if (count === 0) continue;
    detail[name] = count;
    total += count;
  }
  return { total, detail };
};

const runtime = linesOf(runtimeClosure);
const wider = linesOf(withConfigured);

const pilotLines = lineCount(pilotSource);
const pilotTestLines = lineCount(pilotSpec);

const report = {
  note: 'Generated by scripts/pilot-reuse.mjs. Do not edit by hand.',
  pilot: {
    sourceFiles: pilotSource.length,
    sourceLines: pilotLines,
    testFiles: pilotSpec.length,
    testLines: pilotTestLines,
  },
  runtime: {
    describes:
      'The transitive closure of framework packages the pilot’s runtime code imports. This is the payment path.',
    directPackages: [...direct].sort(),
    closureSize: runtimeClosure.size,
    frameworkLines: runtime.total,
    reusePercent: Number(((runtime.total / (runtime.total + pilotLines)) * 100).toFixed(1)),
    byPackage: runtime.detail,
  },
  configured: {
    describes:
      'Packages the pilot configures and exercises but does not import at runtime — the enterprise layer, the product layer and the API gate.',
    packages: [...configured].sort(),
    closureSize: withConfigured.size,
    frameworkLines: wider.total,
    reusePercent: Number(((wider.total / (wider.total + pilotLines)) * 100).toFixed(1)),
  },
};

const out = 'docs/pilot/evidence/framework-reuse.json';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify(report, null, 2)}\n`, 'utf8');

process.stdout.write(
  [
    `pilot source        ${report.pilot.sourceLines} lines in ${report.pilot.sourceFiles} files`,
    `pilot tests         ${report.pilot.testLines} lines in ${report.pilot.testFiles} files`,
    '',
    `runtime closure     ${report.runtime.closureSize} packages, ${report.runtime.frameworkLines} lines`,
    `reuse (runtime)     ${report.runtime.reusePercent}%`,
    '',
    `with configured     ${report.configured.closureSize} packages, ${report.configured.frameworkLines} lines`,
    `reuse (wider)       ${report.configured.reusePercent}%`,
    '',
    `written to ${out}`,
    '',
  ].join('\n'),
);
